name: Java CI

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Compile with Maven
        run: mvn clean compile
            
      - name: Test with Maven
        run: mvn test
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devops-mod8
        
      - name: Package
        run: mvn package
        
      - name: Deploy Prod to Azure
        if: github.ref == 'refs/heads/main'
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: places-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
          
      - name: Deploy Staging to Azure
        if: github.ref != 'refs/heads/main'
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: staging-places-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_STAGING_PROFILE }}
          package: target/*.jar
          
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash    
          
      - name: Test Deployment
        run: mvn test -Dspring.profiles.active=prod